#pragma once

#include "shape.h"
#include "line/straight_line.h"
#include "oval/circle.h"
#include "oval/ellipse.h"
#include "triangle/isosceles_right_triangle.h"
#include "triangle/equilateral_triangle.h"
#include "rect/rectangle.h"
#include "rect/square.h"
#include "n-gon/pentagon.h"
#include "n-gon/hexagon.h"
#include "other/arrow.h"
#include "other/star.h"
#include "other/math/plus.h"
#include "other/math/minus.h"
#include "other/math/multiply.h"
#include "other/math/divide.h"
